version: 2
jobs:
  build:
    docker:
      - image:  circleci/elixir:1.8.0
        environment:
          MIX_ENV: test
      - image: circleci/postgres:11.3-alpine
        enironvment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost

    working_directoy: ~/oceanconnect

    steps:
      - run:
        name: Install Chromedriver
        command: |
          export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
          curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin


      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run: mix deps.get

      - save_cache:  # generate and store mix cache
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:  # make another, less specific cache
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:  # you should really save one more cache (just in case)
          key: v1-mix-cache
          paths: "deps"

      - run: (cd assets && npm install && yarn build)

      - save_cache:  # generate and store mix cache
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths: "deps"

      - run: mix compile

      - save_cache: # don't forget to save a *build* cache, too
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache: # and one more build cache for good measure
          key: v1-build-cache
          paths: "_build"

      - run: mix phx.digest

      - run: export PATH=$PATH:/usr/lib/chromium-browser/
      - run: export DISPLAY=:99.0
      - run: sh -e /etc/init.d/xvfb start
      - run: sleep 3
      - run: nohup chromedriver &
      - run: mix do ecto.create, ecto.migrate


      - run:  # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: mix test  # run all tests in project

      - store_test_results:
          path: _build/test/lib/oceanconnect
