# Web system setup
#
# ansible-playbook -u $USER -v -l web_servers playbooks/letsencrypt.yml -D

- name: Let's Encrypt
  hosts: 'letsencrypt'
  gather_facts: yes
  pre_tasks:
    - name: Install Certbot Nginx Plugin
      raw: apt -y update && apt install -y python-certbot-nginx

  roles:
    - geerlingguy.nginx
    - geerlingguy.certbot

  tasks:
    - name: Ensure docroot exists.
      file:
        path: "{{ nginx_docroot }}"
        state: directory

    - name: Copy Nginx server configuration in place.
      template:
        src: ../templates/https-letsencrypt.conf.j2
        dest: /etc/nginx/sites-enabled/https-letsencrypt.conf
        mode: 0644
      notify: restart nginx
