# These are the default vars that apply to all servers

# OS user account that deploys the app and owns the code files
users_deploy_user: deploy
# OS group for deploy
users_deploy_group: "{{ users_deploy_user }}"

# Firewall settings.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

# Nginx settings.
nginx_vhosts: []
nginx_remove_default_vhost: True
nginx_ppa_use: True
nginx_ppa_version: stable
nginx_docroot: /var/www/html

# Let's Encrypt certificate settings.
certbot_create_if_missing: yes
certbot_auto_renew_options: "--quiet --no-self-upgrade --nginx"
certbot_admin_email: "{{ letsencrypt_email }}"
certbot_certs:
  - domains:
      - "{{ inventory_hostname }}"
