FROM ubuntu:16.04

ARG ANSIBLE_VERSION="2.7.4"
ARG PLAYBOOK_FILE="playbook.yml"

RUN apt-get update -qq && \
    apt-get install -qq sudo python-apt python-pycurl python-pip python-dev libffi-dev libssl-dev && \
    pip install -U setuptools && \
    pip install -q ansible==$ANSIBLE_VERSION && \
    ansible --version

WORKDIR /tmp/ansible-role-asdf
COPY  .  /tmp/ansible-role-asdf

RUN useradd -m vagrant
RUN echo localhost > inventory

RUN ansible-playbook -i inventory -c local tests/$PLAYBOOK_FILE

RUN sudo -iu vagrant bash -lc 'asdf --version'
